documents = [
"Computer science is the study of algorithms, data structures, and the principles of computing systems.",
"An algorithm is a finite set of instructions that solves a specific problem.",
"Big O notation describes the time or space complexity of an algorithm in terms of input size.",
"The binary number system uses base 2, consisting of only 0s and 1s.",
"A compiler translates high-level programming code into machine code executable by hardware.",
"An interpreter executes code line-by-line rather than compiling it in advance.",
"Recursion is a programming technique where a function calls itself to solve smaller instances of a problem.",
"A stack operates on the Last-In-First-Out (LIFO) principle.",
"A queue operates on the First-In-First-Out (FIFO) principle.",
"A linked list is a data structure consisting of nodes that store data and a pointer to the next node.",
"A binary tree is a hierarchical structure where each node has at most two children.",
"A binary search tree (BST) maintains elements in sorted order for efficient insertion and search.",
"A hash table stores key-value pairs and uses a hash function to compute an index for fast retrieval.",
"Sorting algorithms include quicksort, mergesort, heapsort, and bubble sort.",
"Quicksort uses a divide-and-conquer approach and is efficient on average but has O(n^2) worst-case time complexity.",
"Mergesort is a stable, divide-and-conquer sorting algorithm with O(n log n) time complexity.",
"Depth-first search (DFS) explores as far as possible along each branch before backtracking.",
"Breadth-first search (BFS) explores all nodes at the current depth before moving to the next level.",
"A graph can be represented using adjacency lists or adjacency matrices.",
"A directed acyclic graph (DAG) is used in scheduling and dependency modeling.",
"Dynamic programming breaks problems into overlapping subproblems and stores intermediate results.",
"Greedy algorithms make locally optimal choices at each step with the hope of finding a global optimum.",
"A database is an organized collection of data that can be easily accessed, managed, and updated.",
"SQL (Structured Query Language) is used to query and manipulate relational databases.",
"A primary key uniquely identifies each record in a database table.",
"A foreign key enforces relationships between tables in a relational database.",
"Normalization reduces data redundancy in database design.",
"Denormalization improves query performance by combining related tables.",
"Concurrency control in databases ensures correct results in multi-user environments.",
"A transaction in a database must satisfy the ACID properties: Atomicity, Consistency, Isolation, Durability.",
"Operating systems manage hardware, memory, and processes for users and applications.",
"Virtual memory extends physical memory by using disk space as temporary storage.",
"A process is an instance of a running program.",
"A thread is the smallest sequence of programmed instructions that can be managed independently.",
"Deadlock occurs when processes wait indefinitely for each other to release resources.",
"A semaphore is used to control access to shared resources in concurrent programming.",
"A mutex allows only one thread to access a resource at a time.",
"Computer networks allow communication between devices using protocols like TCP/IP.",
"The OSI model has seven layers: Physical, Data Link, Network, Transport, Session, Presentation, and Application.",
"The Internet Protocol (IP) provides addressing and routing for data packets.",
"TCP ensures reliable, ordered data transmission between devices.",
"UDP is a connectionless protocol used for speed over reliability, such as in streaming.",
"A firewall filters network traffic based on predefined rules.",
"Encryption protects data confidentiality by converting information into an unreadable format.",
"Symmetric encryption uses one key for encryption and decryption; asymmetric uses a public-private key pair.",
"RSA and AES are widely used encryption algorithms.",
"A hash function maps data of arbitrary size to a fixed-size value.",
"SHA-256 is a cryptographic hash algorithm used in blockchain systems.",
"A neural network is a model inspired by the human brain, composed of interconnected layers of neurons.",
"A perceptron is the simplest type of neural network that classifies data using a linear boundary.",
"Activation functions like ReLU, sigmoid, and tanh introduce non-linearity to neural networks.",
"A convolutional neural network (CNN) is commonly used for image recognition tasks.",
"A recurrent neural network (RNN) is designed for sequential data like time series or text.",
"Long Short-Term Memory (LSTM) networks mitigate vanishing gradients in RNNs.",
"Transformers use attention mechanisms to process sequences efficiently without recurrence.",
"The attention mechanism weighs the importance of different input tokens for context understanding.",
"GPT (Generative Pretrained Transformer) models use transformer architecture for natural language generation.",
"BERT (Bidirectional Encoder Representations from Transformers) is used for language understanding tasks.",
"Fine-tuning adapts pretrained models to specific downstream tasks using smaller datasets.",
"Transfer learning reuses knowledge from one domain to improve performance in another.",
"Reinforcement learning involves agents that learn optimal actions through trial and reward feedback.",
"Q-learning is a reinforcement learning algorithm that learns a value function for action selection.",
"Deep Q-Networks (DQNs) combine deep learning with reinforcement learning for complex environments.",
"Policy gradient methods directly optimize the policy in reinforcement learning.",
"A loss function measures the difference between model predictions and actual outcomes.",
"Gradient descent is an optimization algorithm that updates parameters to minimize loss.",
"Backpropagation computes gradients for neural network training.",
"Overfitting occurs when a model learns noise instead of patterns from the training data.",
"Regularization techniques like L1, L2, and dropout prevent overfitting.",
"Batch normalization stabilizes and accelerates neural network training.",
"An epoch is one complete pass through the entire training dataset.",
"The learning rate controls how much weights are adjusted during each optimization step.",
"Evaluation metrics for classification include accuracy, precision, recall, and F1 score.",
"Cross-validation assesses model performance by partitioning data into training and validation sets.",
"A confusion matrix summarizes prediction results for a classification problem.",
"Unsupervised learning discovers patterns in unlabeled data.",
"K-means clustering partitions data into k groups based on similarity.",
"Principal Component Analysis (PCA) reduces dimensionality while preserving variance.",
"An autoencoder compresses and reconstructs data for feature learning.",
"Generative Adversarial Networks (GANs) consist of a generator and a discriminator competing to improve output realism.",
"Natural language processing (NLP) enables machines to understand and generate human language.",
"Tokenization splits text into smaller units like words or subwords.",
"Word embeddings represent words as dense vectors capturing semantic meaning.",
"Sentence transformers encode entire sentences into numerical embeddings.",
"Named entity recognition identifies entities like names, dates, and locations in text.",
"Text summarization condenses large documents into concise summaries.",
"Sentiment analysis determines the emotional tone of text.",
"Chatbots use NLP and dialogue models to interact with users conversationally.",
"Speech recognition converts spoken language into text.",
"Text-to-speech (TTS) systems synthesize human-like voice output from text.",
"Computer vision enables machines to interpret images and videos.",
"Object detection identifies and locates objects within an image.",
"Image segmentation classifies each pixel in an image by object or region.",
"Optical character recognition (OCR) extracts text from images.",
"Edge detection identifies boundaries between regions in an image.",
"Reinforcement learning is used in robotics for path planning and control.",
"Autonomous vehicles use computer vision, sensor fusion, and AI to navigate environments.",
"Explainable AI (XAI) seeks to make AI model decisions understandable to humans.",
"Ethical AI emphasizes fairness, transparency, and accountability in AI systems.",
"Bias in AI occurs when training data reflects societal or measurement biases.",
"Federated learning trains models across decentralized devices without sharing raw data.",
"Edge AI runs machine learning models on local devices for low-latency decision-making.",
"Quantum computing uses quantum bits that can exist in multiple states simultaneously.",
"Superposition and entanglement are key principles of quantum mechanics used in computation.",
"Quantum algorithms like Shor’s and Grover’s can outperform classical algorithms for specific problems.",
"Cloud computing provides on-demand access to computing resources over the internet.",
"Serverless computing allows developers to run code without managing servers.",
"Containers like Docker package applications and dependencies for consistent deployment.",
"Kubernetes automates container orchestration and scaling in distributed environments.",
"APIs enable different software systems to communicate and exchange data.",
"RESTful APIs use HTTP methods like GET, POST, PUT, and DELETE.",
"GraphQL allows clients to query only the data they need from APIs.",
"Machine learning pipelines automate preprocessing, training, and deployment steps.",
"MLOps integrates machine learning with DevOps for continuous model delivery.",
"Data preprocessing involves cleaning, normalizing, and transforming data before training.",
"Feature engineering creates informative features to improve model performance.",
"Hyperparameter tuning finds the best configuration for model performance.",
"AI evaluation must consider bias, robustness, and generalization."
"Finance is the study of money management, investments, and financial systems.",
"The three main areas of finance are personal finance, corporate finance, and public finance.",
"The time value of money states that a dollar today is worth more than a dollar tomorrow.",
"Compound interest is interest calculated on the initial principal and accumulated interest from previous periods.",
"The formula for compound interest is A = P(1 + r/n)^(nt).",
"Simple interest is calculated only on the principal, using the formula I = P * r * t.",
"An asset is anything of value owned by an individual or company.",
"A liability is a financial obligation or debt owed to another party.",
"Equity represents ownership in an asset after deducting liabilities.",
"A balance sheet shows a company’s assets, liabilities, and shareholders’ equity at a specific point in time.",
"An income statement reports revenue, expenses, and profits over a period.",
"A cash flow statement tracks cash inflows and outflows from operating, investing, and financing activities.",
"Liquidity measures how easily an asset can be converted into cash.",
"Leverage refers to using borrowed capital to increase potential returns.",
"A company’s market capitalization equals its share price multiplied by total outstanding shares.",
"The price-to-earnings (P/E) ratio measures how much investors pay for one dollar of earnings.",
"A low P/E ratio may indicate undervaluation, while a high P/E ratio may suggest growth expectations.",
"Earnings per share (EPS) measures a company’s profitability per outstanding share.",
"Return on equity (ROE) indicates how efficiently a company uses shareholders’ equity to generate profit.",
"Return on assets (ROA) shows how efficiently assets are used to produce income.",
"Debt-to-equity ratio compares a company’s total liabilities to its shareholder equity.",
"Current ratio measures short-term liquidity by comparing current assets to current liabilities.",
"A dividend is a distribution of profits paid to shareholders.",
"The dividend yield equals annual dividend per share divided by stock price.",
"Blue-chip stocks are shares of large, established, and financially stable companies.",
"Growth stocks belong to companies expected to grow faster than the market average.",
"Value stocks trade below their intrinsic value based on fundamental analysis.",
"Penny stocks are low-priced, speculative securities with high volatility.",
"A bond is a fixed-income instrument representing a loan made by an investor to a borrower.",
"The coupon rate is the annual interest paid by a bond issuer to bondholders.",
"The yield to maturity (YTM) represents the total return expected if a bond is held until maturity.",
"Government bonds are issued by national governments and are considered low-risk.",
"Corporate bonds are issued by companies to raise capital and carry credit risk.",
"Municipal bonds are issued by local governments and often provide tax advantages.",
"Stock exchanges like the NYSE and NASDAQ facilitate trading of securities.",
"A stock index tracks the performance of a group of related stocks, such as the S&P 500 or Dow Jones.",
"The S&P 500 includes 500 of the largest U.S. publicly traded companies.",
"The NASDAQ is known for technology-oriented and growth companies.",
"A bull market is characterized by rising stock prices and investor optimism.",
"A bear market involves falling prices and widespread pessimism.",
"Volatility measures how much an asset’s price fluctuates over time.",
"Beta measures a stock’s volatility relative to the overall market.",
"A diversified portfolio spreads investments across different assets to reduce risk.",
"Asset allocation divides a portfolio among asset classes like stocks, bonds, and cash.",
"Modern Portfolio Theory (MPT) optimizes portfolio risk and return through diversification.",
"The efficient frontier shows the set of portfolios offering the highest expected return for a given risk.",
"Risk tolerance is the degree of variability in investment returns an investor is willing to withstand.",
"Systematic risk affects the entire market, while unsystematic risk is company-specific.",
"A hedge is an investment designed to reduce potential losses from another position.",
"Hedging strategies use derivatives like options and futures to manage risk.",
"An option gives the holder the right, but not the obligation, to buy or sell an asset at a set price.",
"A call option gives the right to buy an asset, while a put option gives the right to sell it.",
"The strike price is the agreed price at which an option can be exercised.",
"The expiration date is when an option contract becomes void.",
"Intrinsic value measures how much an option is in-the-money.",
"Implied volatility reflects the market’s expectations for future price fluctuations.",
"Futures contracts obligate the buyer to purchase, and the seller to deliver, an asset at a future date and price.",
"A forward contract is similar to a future but traded over-the-counter rather than on an exchange.",
"A swap is a derivative contract where two parties exchange cash flows or financial instruments.",
"A margin account allows investors to borrow funds from a broker to trade securities.",
"Short selling involves borrowing a stock to sell it, hoping to buy it back later at a lower price.",
"A stop-loss order automatically sells a security when it reaches a predetermined price.",
"Limit orders execute trades only at a specified price or better.",
"Market orders execute immediately at the current market price.",
"Day trading involves buying and selling financial instruments within the same trading day.",
"Swing trading holds positions for several days to capture short-term market movements.",
"Position trading involves holding investments for weeks or months to capitalize on broader trends.",
"Technical analysis studies price charts and indicators to predict market movements.",
"Fundamental analysis evaluates a company’s intrinsic value based on financial health and performance.",
"Support and resistance levels indicate price zones where assets repeatedly stop falling or rising.",
"Moving averages smooth price data to identify trends.",
"The relative strength index (RSI) measures momentum and signals overbought or oversold conditions.",
"The moving average convergence divergence (MACD) shows the relationship between two moving averages.",
"The Bollinger Bands indicator measures price volatility around a moving average.",
"Volume measures the number of shares traded in a given period and helps confirm price trends.",
"A candlestick chart shows open, high, low, and close prices for a given time period.",
"A doji candlestick indicates market indecision and potential reversal.",
"A hammer candlestick suggests potential bullish reversal after a downtrend.",
"A shooting star indicates potential bearish reversal after an uptrend.",
"Market capitalization categories include small-cap, mid-cap, and large-cap stocks.",
"Initial Public Offerings (IPOs) allow companies to sell shares to the public for the first time.",
"Private equity involves investing in companies not listed on public exchanges.",
"Venture capital provides funding to early-stage, high-growth startups.",
"Hedge funds use complex strategies to achieve returns regardless of market direction.",
"Mutual funds pool money from investors to buy a diversified portfolio of assets.",
"Exchange-traded funds (ETFs) trade on exchanges and track an index, sector, or commodity.",
"Index funds aim to replicate the performance of a specific market index.",
"Real estate investment trusts (REITs) allow investors to gain exposure to income-producing real estate.",
"Commodities include physical goods like gold, oil, and agricultural products.",
"Gold is often used as a hedge against inflation and currency devaluation.",
"Cryptocurrencies are decentralized digital assets secured by blockchain technology.",
"Bitcoin was the first cryptocurrency, created in 2009 by Satoshi Nakamoto.",
"Ethereum introduced smart contracts and decentralized applications (dApps).",
"Blockchain is a distributed ledger that records transactions across multiple computers.",
"DeFi (Decentralized Finance) enables financial transactions without intermediaries using blockchain.",
"Stablecoins are cryptocurrencies pegged to stable assets like the U.S. dollar.",
"Market sentiment reflects investors’ collective attitude toward risk and market direction.",
"Fear and greed indices measure investor emotions and market volatility.",
"Inflation is the rate at which the general level of prices for goods and services rises over time.",
"Deflation is a decrease in the general price level of goods and services.",
"The Consumer Price Index (CPI) measures inflation by tracking changes in consumer goods prices.",
"The Producer Price Index (PPI) measures average changes in selling prices by producers.",
"The Federal Reserve controls U.S. monetary policy and influences interest rates.",
"Interest rates affect borrowing costs, consumer spending, and investment activity.",
"The yield curve plots interest rates of bonds with different maturities.",
"An inverted yield curve can signal an upcoming economic recession.",
"Gross Domestic Product (GDP) measures the total value of goods and services produced in a country.",
"Unemployment rate indicates the percentage of the labor force that is jobless and actively seeking work.",
"Fiscal policy involves government spending and taxation to influence the economy.",
"Monetary policy involves managing money supply and interest rates to achieve economic stability.",
"Quantitative easing involves central banks purchasing financial assets to inject liquidity into the economy.",
"A recession is a significant decline in economic activity across the economy lasting more than a few months.",
"A depression is a severe and prolonged economic downturn.",
"A bull trap occurs when prices rise briefly during a downtrend before continuing lower.",
"A bear trap occurs when prices fall temporarily during an uptrend before rebounding higher.",
"Market capitalization-weighted indexes assign more weight to larger companies.",
"Equal-weighted indexes assign equal importance to all constituent stocks.",
"High-frequency trading (HFT) uses algorithms to execute trades in milliseconds.",
"Algorithmic trading uses preprogrammed strategies to automate buying and selling decisions.",
"Quantitative trading relies on mathematical and statistical models to identify opportunities.",
"Value investing focuses on buying undervalued stocks based on fundamentals.",
"Growth investing targets companies with strong earnings growth potential.",
"Dividend investing seeks stocks with regular and growing dividend payments.",
"Index investing tracks the performance of major market indices like the S&P 500.",
"Momentum investing buys assets that have shown recent strength and sells those showing weakness.",
"Contrarian investing goes against prevailing market trends to exploit overreactions.",
"Technical indicators include RSI, MACD, stochastic oscillator, and Bollinger Bands.",
"Risk-adjusted return measures how much return an investment generates for its level of risk.",
"The Sharpe ratio measures excess return per unit of risk.",
"The Sortino ratio focuses on downside risk rather than total volatility.",
"The Treynor ratio measures returns earned in excess of the risk-free rate per unit of market risk.",
"The alpha of a portfolio measures its performance relative to a benchmark after adjusting for risk.",
"Beta measures sensitivity of an asset’s returns relative to market movements.",
"A portfolio’s diversification reduces unsystematic risk but cannot eliminate systematic risk.",
"Correlation measures the degree to which two assets move together.",
"Negative correlation between assets improves diversification benefits.",
"Rebalancing involves adjusting portfolio weights to maintain target asset allocation.",
"Tax-loss harvesting involves selling losing investments to offset taxable gains.",
"Inflation erodes the real value of money over time.",
"Defensive stocks tend to perform well during economic downturns.",
"Cyclical stocks rise and fall with the business cycle.",
"Interest rate hikes generally reduce bond prices and can slow economic growth.",
"Exchange rates influence the value of international investments.",
"The foreign exchange (forex) market is the largest and most liquid financial market in the world.",
"The U.S. dollar is the world’s primary reserve currency.",
"Emerging markets offer higher growth potential but also higher risk.",
"A diversified global portfolio can reduce country-specific risks.",
"Behavioral finance studies how psychology affects investor decision-making.",
"Herd behavior leads investors to follow market trends irrationally.",
"Loss aversion causes investors to fear losses more than they value equivalent gains.",
"Overconfidence can lead to excessive trading and risk-taking.",
"Anchoring bias makes investors rely too heavily on initial information.",
"Confirmation bias causes investors to seek information that supports existing beliefs.",
"Financial literacy improves long-term investment outcomes and decision-making."
]
